### ISSUE TITLE
Wording in intermediate "Order"-step

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/archigator-backend#3]
I would change the following words so that it is clear to the user what each point means:

- Order -> Publication Request
- Order - > Preliminary Publication ID
- Project -> Investigation
- Project Owner -> Corresponding Author (This should be the person who published it. In my case it shows Lukas although I triggered the process.)

![image](https://github.com/nfdi4plants/archigator/assets/74731649/9e54698d-a9ca-4fea-8517-d27430a2feb5)

**Comment by Zerskk** [comment]
Project Owner:  it is not possible to show the person who published it, because of lacks in the API of Invenio (or Gitlab). But instead we can show a list of authors or gitlab members

**Comment by CMR248** [comment]
I would suggest to just skip this point

**Comment by Zerskk** [comment]
Project owner is now removed. The other suggestions are now implemented.
