### ISSUE TITLE
[bug] allow publication of group ARCs

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/archigator-backend#7]
I'm getting an error when trying to publish an ARC that belongs to a group: 

https://git.nfdi4plants.org/hhu-plant-biochemistry/2015_NasserSewelam_DominikBrilhaus

- the ARC is public 
- I created it and pushed to group (https://git.nfdi4plants.org/hhu-plant-biochemistry/) in which I have role "owner"

<img width="726" alt="Screenshot 2023-09-14 at 14 04 01" src="https://github.com/nfdi4plants/archigator-backend/assets/16229676/da419f4c-7a76-4592-8af6-e677172e2457">

**Comment by Brilator** [comment]
Can you check this out again? @Zerskk 
I cannot publish ARCs that are stored under a namespace (e.g. group) other than my user name.

**Comment by Zerskk** [comment]
This is intentional. Only members of a project can publish ARCs.

**Comment by Brilator** [comment]
But I own them. 
I am owner of the ARC and owner of the group

**Comment by Zerskk** [comment]
My guess is that this is because you are accessing the project from a group. archigator only checks the project membership, not the group membership. this is a bug.

**Comment by Zerskk** [comment]
bug is fixed, groups are now reconsidered. issue closed
