### ISSUE TITLE
Bad gateway error on publishing

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/archigator-backend#9]
Hi Team,

Not sure if this is the right place to report this, but I am getting a "Bad gateway" error when I try to publish my ARC from DataHUB by clicking on the (passing) invenio badge. I tested the process last week and it was working fine, nothing has changed in my arc since.

**Comment by j-bauer** [comment]
Hi, sorry for the late answer. Not sure how long the problem persisted but archigator is back up now. Everything should work again.

**Comment by shiltemann** [comment]
@j-bauer thanks a lot, can confirm it works for me again :+1:

**Comment by j-bauer** [comment]
Great, I'll close this issue then.
